name: NetFrameWork.Legacy.CI

on: 
  push:
    branches: 
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Restore packages
      run: nuget restore src/HelperKit/HelperKit.sln

    #- name: Setup MSBuild.exe
      #uses: microsoft/setup-msbuild@v1.1.1

    #- name: Build with MSBuild
      #run: msbuild src/HelperKit/HelperKit.sln -p:Configuration=Release
      
    - name: Build
      run: dotnet build src/HelperKit/HelperKit.sln --no-restore -c Release
      
    - name: dotnet test
      run: dotnet test src/HelperKit/HelperKit.sln --no-restore --verbosity normal
